osx_image: xcode8
language: objective-c
rvm: 2.2.2

env:
  global:
  - FRAMEWORK_NAME=AsyncTask

#branches:
#  only:
#  - master

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build test -project AsyncTask.xcodeproj -scheme 'AsyncTaskOSXTests' 
- pod lib lint AsyncTask.podspec

before_deploy:
- carthage build --no-skip-current --platform osx, ios
- carthage archive $FRAMEWORK_NAME

deploy:
  provider: releases
  api_key:
    secure: TuZu5MlLeRdHlIX1PquhQzqXNgMpMUq9+b7HxjcqtEv8zUiQWQjoaXdDhgJ2AIWK+XM6WSrzolorsNXgILYcR9B/UTv017gu5D7RF4VROcpsTyi2rgrfBVeaNMMNVAPfGAykHxskfvVvXrTRU1Bp6GGVLE5hxFx/skkgtB/lZxJWhDQXytijROdnb+ITTqkEapmRbp/ACvcDrAHpFVzcZ2r20VRJK23mA2jSJL4hX8GraKzwgjPmcoVt67EDMnnhUDbMx9vL4QGnbpeKFDP7uYtgfme64mbAsbCvtFP89qPndLnvESl0Sn0g2nqBFSqiSk3lAspi1NobZVmmI3xiHrYebJLAYrQzu7PbT467iGSvN8UFL91o/rUTrV7V+fuvqEAD/2ESHEx/XCm+pfix60PKCiku+BNytWZFOtuobMo1RimUazkX87GZkHFUIWIyL/U1QC8D9D6dmkEvJJrW0ZFbIMaAZ45bTLqcWeQFVL7EH06u7Wc3dsUSQMNlXqxaI42tJ708Rtp0+iP9zj9zIP7BNFpUiLOsseKBMZTuHsCj90A/L5P2GRr1I52/rR4skov6/PHmpnur9+WMrutkLnFJ/dAlPKXMDx5R3ZK3I13iZuBHAbo4gFrnEZkjZ7N0QamSAQxD7LK6phBp1n+yuNM2LUWVq3KqdDOdlM7+EUs=
  file: AsyncTask.framework.zip
  skip_cleanup: true
  on:
    repo: stendahls/AsyncTask
    tags: true

